name: Fix locale issues

on:
  push:
    branches: [ master ]
    paths:
      - '**.xml'
  workflow_dispatch:

concurrency:
  group: "locale"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        token: ${{ secrets.REPO_TOKEN }}

    - name: Install dependencies
      run: pip3 install lxml requests

    - name: Edit files
      run: python3 .github/locales.py

    - name: Commit to the repo
      run: |
        git config --local user.email "111277985+mehdigm[bot]@users.noreply.github.com"
        git config --local user.name "mehdigm[bot]"
        git add .
        # "echo" returns true so the build succeeds, even if no changed files
        git commit -m 'chore(locales): fix locale issues' || echo
        git push
